//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Descriptions { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Sold { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
